### Loading Varaiables
@OPENAI_API_KEY=<>
@WEAVIATE_URL=<>
@CSV_FILE_LOCATION=./01-data/master_table_column_comments.csv
@MASTER_CLASS_NAME=Master


### Getting list of Schema
GET {{WEAVIATE_URL}}/v1/schema

### Delete Account Schema
DELETE  {{WEAVIATE_URL}}/v1/schema/Account

### Delete Master Schema
DELETE  {{WEAVIATE_URL}}/v1/schema/Master

### Delete HistoryText Schema
DELETE  {{WEAVIATE_URL}}/v1/schema/HistoryText